# Generated by Django 6.1.1 on 2026-10-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcsscrapper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='file_modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='order_date_str',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
