# Generated by Django 6.1.1 on 2026-10-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcsscrapper', '0002_receipt_file_modified_at_receipt_order_date_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
