# Generated by Django 6.1.1 on 2026-10-03 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcsscrapper', '0004_roommate_email_roommate_user_expense_expensesplit'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Groceries', 'Groceries'), ('Utilities', 'Utilities'), ('Rent', 'Rent'), ('Dining', 'Dining Out'), ('Entertainment', 'Entertainment'), ('Household', 'Household Supplies'), ('Transportation', 'Transportation'), ('Furniture', 'Furniture'), ('Gifts', 'Gifts'), ('Payment', 'Payment')], default='General', max_length=50),
        ),
    ]
