# Generated by Django 6.1.1 on 2026-10-04 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcsscrapper', '0005_roommate_is_active_alter_expense_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseholdGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('group_type', models.CharField(choices=[('home', 'Apartment / House'), ('trip', 'Trip / Vacation'), ('other', 'Other Group')], default='home', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to='rcsscrapper.roommate')),
                ('members', models.ManyToManyField(blank=True, related_name='groups', to='rcsscrapper.roommate')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='rcsscrapper.householdgroup'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='rcsscrapper.householdgroup'),
        ),
    ]
